### ISSUE TITLE
string[index] doesn't work correctly

### ISSUE THREAD

**Issue by ngocdaothanh** [codecombat/esper.js#16]
See the line `console.log(string, i, char)` below in the program to check if parentheses are balanced:

```
function check(string) {
  let count = 0

  for (let i = 0; i < string.length; i++) {
    const char = string[i]
    console.log(string, i, char)

    if (char === '(')
      count++
    else if (char === ')')
      count--

    console.log(count)
    if (count < 0) return false
  }

  return count === 0
}

console.log(check('()(()())'))
```

Expected output:
```
()(()()) 0 (
()(()()) 1 )
()(()()) 2 (
...
```

Actual output:
```
()(()()) 0 (
()(()()) 1 (
()(()()) 2 (
...
```

It seems that in this program `string[index]` always returns the first character.

**Comment by basicer** [comment]
The problem here is that ES6 block scoping isn't implemented yet, so the const applies to the whole function, and the assignment silently fails. Fixing #15 will make this more obvious.

**Comment by ngocdaothanh** [comment]
I think there's bug somewhere, because when the program is in ES5, it doesn't work as expected:

```
function check(string) {
  var count = 0

  for (var i = 0; i < string.length; i++) {
    var char = string[i]
    console.log(string, i, char)

    if (char === '(')
      count++
    else if (char === ')')
      count--

    if (count < 0) return false
  }

  return count === 0
}

console.log(check('()(()())'))
```

**Comment by ngocdaothanh** [comment]
I've just try running with the demo site again:
https://esper.js.org

The output looks good now. So it was because of the `const` problem as you explained.
