### ISSUE TITLE
Cannot catch load error

### ISSUE THREAD

**Issue by ngocdaothanh** [codecombat/esper.js#17]
With the latest master code, the log below is not printed:

```
var engine = esper({});
try {
  engine.load('invalid code');
} catch (e) {
  console.log('Error: ' + e);
}
```

**Comment by ngocdaothanh** [comment]
I'm trying in a ReactJS program, running in Chrome browser.

Replace `'invalid code'` with `'xxx'` and you may be able to see this log (I see it it Chrome console):

```
esper.js:8195 Uncaught ReferenceError: xxx is not defined
    at xxx (:3000/<src>:1)
```

I think the error is logged by esper.js, but esper.js does not throw out the error.

**Comment by basicer** [comment]
`xxx` as code results in a runtime error.  It is valid javascript code, it gets the value of xxx and throw's it away.  `invalid code` is a compile error, so it its throw when you `.load()` while `xxx` errors during execution.

**Comment by ngocdaothanh** [comment]
Ah thanks! It makes sense now.

So I'll need to catch the error when call, for example, `engine.step()`.
