### ISSUE TITLE
run() stops after FutureValue resolves

### ISSUE THREAD

**Issue by flx5** [codecombat/esper.js#19]
Hi there,
it seems like esper.js stops interpretation once it reaches a FutureValue.
When the promise resolves, run terminates.

The following code prints 42 onto the console instead of 43, and further testing revealed that anything called after test() won't be executed anymore.

```
var engine = esper({

});

function test() {
    return esper.FutureValue.make(
        new Promise((resolve) => {
            setTimeout(resolve, 1000);
        }).then(() => 42)
    );
}

engine.addGlobalFx('test',
    test
);
engine.load('test(); 43;');

engine.run().then((result: any) => {
    console.log(result.toNative());
});
```

**Comment by basicer** [comment]
What version of esper.js are you using?  e49f15816e0e92f7a046d633c414dacf9f1a1b7b prints 43 in console for me with node `v8.9.1`
