### ISSUE TITLE
new Date

### ISSUE THREAD

**Issue by supipd** [codecombat/esper.js#6]
I don`t know, how expose native Date to tested code. 
Trying addGlobalFx('Date',Date) results in 'TypeError: function is not a constructor(…)'
Uncomment scope.set('Date', this.fromNative(Date)) results 'Uncaught TypeError: Tried to load an unsafe native value into the interperter:function / function Date() { [native code] }'

Any overwork ?

**Comment by basicer** [comment]
Sorry I didn't see this sooner.

`addGlobalFx` doesn't currently work for constructors.  I'll get this fixed in the next version.

**Comment by basicer** [comment]
Also `addGlobal('Date',Date')` might do what your looking for.

**Comment by supipd** [comment]
Confirmed. `addGlobal('Date',Date)` works great. Thanks.
